### ISSUE TITLE
Not work on FreeBSD (non linux ?)

### ISSUE THREAD

**Issue by bapt** [stransky/wayland-proxy#3]
I can't get this code working as expected on freebsd, it never ever tries to connect to the compositor, after some debugging I figured the issue seems to be here: https://github.com/stransky/wayland-proxy/blob/main/src/wayland-proxy.cpp#L329 

If I remove that test everything works as expected.

Am I missing something obvious?

**Comment by stransky** [comment]
Hm, no idea. POLLOUT should be supported on FreeBSD.

**Comment by bapt** [comment]
POLLOUT is supported, my question is how revents can be set to pollout before any connection? if my understanding is correct here we have:

fd = socket(AF_UNIT)
poll(fd)
if (fd.revent & POLLOUT) => connect

so we cannot connect if we haven't received a POLLOUT on the fd, but we cannot receive one if we are not connected right?

**Comment by bapt** [comment]
so it seems like we have a difference of behaviour between linux and freebsd here

On Linux I have:

socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
wait4(157739, 0x7ffc0cb4e360, WNOHANG|WSTOPPED|WCONTINUED, NULL) = 0
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLOUT}], 2, 30000) = 2 ([{fd=4, revents=POLLIN}, {fd=5, revents=POLLOUT|POLLHUP}])

On FreeBSD I have no events for fd=5

**Comment by bapt** [comment]
reading at the socket(2) manpage on linux I can read this for SOCK_STREAM:

```
A stream socket must be in a connected state before any data may be sent or received on it
```
Which sounds sane to me, which means (my interpretation) you are not supposed to expect a POLLOUT on a non connected socket.

**Comment by stransky** [comment]
Cool, thanks for the investigation. Do you mind to create a patch for it?
Thanks.

**Comment by bapt** [comment]
Sure I ll do that

**Comment by bapt** [comment]
https://github.com/stransky/wayland-proxy/pull/6

**Comment by bapt** [comment]
thanks a lot for quick merges!
